# os: osx
sudo: required
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install: skip
jobs:
  include:
  - stage: dependencies
    script:
      - npm i
    name: Setup
  - stage: build
    script:
      - npm run build
    name: Build
