sudo: required
language: node_js
node_js:
  - '8'
# services:
#   - docker
addons:
  #  chrome: stable
  # sonarcloud:
  #   organization: "sreerampr-github"
cache:
  directories:
    - node_modules
    - mycache
install:
  - npm i
  - npm install -g codecov
jobs:
  include:
  - stage: lint
    script:
      - rm -rf mycache
      - mkdir mycache
      - npm run lint:local
    name: Lint
  - stage: test
    script:
      - npm run test
      - mv dist mycache
    name: Unit Test
    after_success: codecov --disable=gcov --file=mycache/dist/test/lcov.txt
  - stage: sonar
    script:
      - npm run sonar
    name: Sonar analysis
  - stage: documentation
    script:
      - npm run styleguide:eject
      - mv styleguide mycache/dist
    name: Documentation
  - stage: build
    script:
      - npm run build
      - cp -a dist/. mycache/dist/
    name: Build
  - stage: Stage
    script:
      # - sh ./scripts/heroku_stage_container.sh
      - sh ./scripts/heroku_stage.sh
    name: Stage (Heroku)
    after_success:
    - npm run lighthouse:pr -- https://sreeram-stage.herokuapp.com
  - stage: performance
    script:
      - npm run lighthouse --  https://sreeram-stage.herokuapp.com --output-path=./mycache/dist/lighthouse.html --quiet --chrome-flags="--headless --no-sandbox"
    name: Lighthouse
  - stage: Host
    script:
      - mv mycache/dist dist
      - npm run firebase:deploy
    name: Host (Firebase)
