sudo: required
language: node_js
node_js:
  - '8'
services:
  - docker
addons:
  chrome: stable
cache:
  directories:
    - node_modules
    - mycache
install: npm install
jobs:
  include:
  - stage: lint
    install:
    - rm -rf mycache
    - mkdir mycache
    script: npm run lint:local
    name: Lint
  - stage: test
    script:
      - npm run test
      - mv dist mycache
    name: Unit Test
  - stage: build
    script:
      - npm run build
      - mv dist mycache
    name: Build
  - stage: Stage
    script: sh ./scripts/heroku_stage.sh
    name: Stage (Heroku)
    after_success:
    - npm run lighthouse:pr -- https://sreeram-stage.herokuapp.com
  - stage: performance
    script:
      - npm run lighthouse --  https://sreeram-stage.herokuapp.com --output-path=./mycache/dist/lighthouse.html --quiet --chrome-flags="--headless --no-sandbox"
    name: Lighthouse
  - stage: Host
    script:
      - mv mycache/dist dist
      - npm run firebase:deploy
    name: Host (Firebase)
