sudo: required
language: node_js
node_js:
  - '8'
# services:
#   - docker
addons:
  #  chrome: stable
cache:
  directories:
    - node_modules
    - mycache
install:
  - npm i
  - npm install -g codecov codeclimate-test-reporter codacy-coverage
jobs:
  include:
  - stage: lint
    script:
      - rm -rf mycache
      - mkdir mycache
      - npm run lint:local
    name: Lint
  - stage: test
    script:
      - npm run test
      - mv dist mycache
    name: Unit Test, Coverage reports (Codecov, Codeclimate, Codacy, Sonar)
    after_success:
      - codecov --disable=gcov --file=mycache/dist/test/lcov.txt
      - codeclimate-test-reporter < mycache/dist/test/lcov.txt
      - codacy-coverage --accountToken $CODACY_TOKEN --username $CODACY_USERNAME --projectName $CODACY_PROJECT < mycache/dist/test/lcov.txt
      - npm run sonar
  - stage: Browserstack
    script:
      - npm run test:browserstack
    name: Browserstack tests
  - stage: documentation
    script:
      - npm run styleguide:eject
      - mv styleguide mycache/dist
    name: Documentation
  - stage: build
    script:
      - npm run build
      - cp -a dist/. mycache/dist/
    name: Build
  - stage: Stage
    script:
      # - sh ./scripts/heroku_stage_container.sh
      - sh ./scripts/heroku_stage.sh
    name: Stage (Heroku)
    after_success:
    - npm run lighthouse:pr -- https://$HEROKU_APP_NAME.herokuapp.com
  - stage: performance
    script:
      - npm run lighthouse --  https://$HEROKU_APP_NAME.herokuapp.com --output-path=./mycache/dist/lighthouse.html --quiet --chrome-flags="--headless --no-sandbox"
    name: Lighthouse
  - stage: Host
    script:
      - mv mycache/dist dist
      - npm run firebase:deploy
    name: Host (Firebase)
    if: branch = master
