FROM node:latest
WORKDIR /usr/src/app
ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm i
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/
WORKDIR /opt/app
ADD .babelrc /opt/app/.babelrc
ADD src /opt/app/src
ADD webpack /opt/app/webpack
ADD server /opt/app/server
RUN ./node_modules/.bin/webpack --env=prod  --config=webpack/webpack.config.js
CMD [ "node", "server/"]
